### ISSUE TITLE
RFE:  tuning options

### ISSUE THREAD

**Issue by kfiresmith** [nickjeffrey/check_disk_io#1]
Hello!
I wanted to start by saying that I'm thrilled to have found your Nagios plugins collection, there's a lot of great stuff in here.

This particular plugin could be even more useful if I could do some check tuning, namely:
*  warn/crit thresholds
*  disk exclusion or filesystem type exclusion (eg loop devices)
*  disk inclusion (same as above but inverse to)

Thanks so much either way for all of these great checks.  If I was any good at perl I'd try to contribute these features.

 - Kodiak

**Comment by nickjeffrey** [comment]
I have added the --latency=##  and --exclude=device1,device2 and --include=device1,device2  parameters, please see readme for usage options

**Comment by nickjeffrey** [comment]
Thanks for the feedback.  I’ve been using some of these plugins for years, but only recently posted them to github, so they have received very little peer review so far.

 

I’m pretty open to making useful enhancements, so feel free to open more feature requests on github.

 

From: Kodiak Firesmith ***@***.***> 
Sent: Friday, December 30, 2022 1:42 PM
To: nickjeffrey/check_disk_io ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nickjeffrey/check_disk_io] RFE: tuning options (Issue #1)

 

Hello!
I wanted to start by saying that I'm thrilled to have found your Nagios plugins collection, there's a lot of great stuff in here.

This particular plugin could be even more useful if I could do some check tuning, namely:

*	warn/crit thresholds
*	disk exclusion or filesystem type exclusion (eg loop devices)
*	disk inclusion (same as above but inverse to)

Thanks so much either way for all of these great checks. If I was any good at perl I'd try to contribute these features.

*	Kodiak
